rvm: 2.6.0
services:
- postgresql
script:
- mkdir -p spec && bundle exec rspec spec
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
- gem update --system
- gem install bundler
before_script:
- psql -c 'create database pgapp_test;' -U postgres
- psql -d pgapp_test -c 'CREATE TABLE "posts" ("id" SERIAL PRIMARY KEY, "message"
  VARCHAR(200), "created_at" TIMESTAMP, "updated_at" TIMESTAMP);'
deploy:
  provider: heroku
  api_key:
    secure: jo1R3ma409JhsL/iAB7sFHT7AEBAlLOaqDRrFAN+wRmyZ0gCys0klolu38HwNCuvZDwPlg1+zQdp6ODQPgnt910gU/OOZUPEg+ISpTKKtZ/2EnfQO9lmC50mczlgBdj1h91PnkJNCg2e+VF4KzZ3PhTCjlQLSlsz0jw3/TcXllQSq9vNT9MSv1Z0vOvAYA+aITA1jI1iN/RzDJOpDIqyRXNs6NJ5sVrQepKap5iiEJBU7HoMRYHuaguFwETQUtlGkhaViyyHRcmSDLPGuJZmhgLwni/9qnVtyabT/cuJkMCwnEopwZwo4PeO2OJfJSCEk4D2JtOKqruFpcwast/G/q/eTp4UU5YJsC9TZjT5UwZXLmQSOzcuMmWW7ZfLlUUJkymCshiWJbcKiH/5mryKNSM5v61o+xdLfUqnhdJzp/TuBRC/5E7/ZHyAGjv6mVBlSuYRKtnI09n9UwCyUd4V4yvY5QrZYcZYgiWSDFcwtuKcrC7+C7htgope6r14fl/uQLJKpdf/MiuLaebjM4ryGx4PH3fMU+mXZ3IiEczC8qbZ1kwf1ERg1c6mT6MJcYrFe7lbDfmCNP6kgElV5iYUERuQJ5Ejc7PSegoH1qy5IC7AFpgLrvmVPRYEJU/qn23bQl4zgKCUK34/2ceojC7gkBzwD0QgOoY07f5QnYJTPgM=
  app: acebook-bcds
  on:
    repo: soroushh/acebook-bcds
