rvm: 2.6.0
services:
- postgresql
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
- gem update --system
- gem install bundler
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rake spec
deploy:
  provider: heroku
  api_key:
    secure: A1wXesHvW2b4MWCxj0oCN1zhFa081wv3EQ7Z9YAZ5Vy4e7rahbyvInCdb5PIUxDv9KQXjBXMxVf5vaMXAcj03GZ4jOTyW9JB3vsYHZEqQVP8DTf/jWm3gCuJPIWKU/Nfz784431RP9BhtIqwM7SPoYzdPHqXQEqDnN7ZfPltIMUTe1YKi19cloB1glNEN7Hr+rQ/quZ8shzTQ989hvJbCP8RaqKiXDYwdZ7Dp6jmjQP16VwBQ9IrntYmXoZG6IqrRURhs3oR5UiNdloQbu4gwfLfGUOFP7cCGSvRw4h3lhJ+jONIMzrWZ5AWzZ+Xd9V0ZcEYIIBfQYGmnsMXGynQZUknESW7rOSRYea/175o4v0sB3ASgKgeQhtXmfe4NQkzntc1hYNzFA4WbwDXocMvtFBHdgPkt3xUqIQzuc++vyoLq2drwFeKLwoE53zz0fw6HIVmRqTWum2BEEhYyeHvjTEU5ez+nDW4hnOE1yPliPJ708o7g21AJ3B2yzEMhXLjoeyeutmfiAi/d1vfYb50VCYxl9lKekihKB48FsixgPSjN35zNaGMMGpvB5iEvD1Icftk3uv7WxBk95j3PqvqhrBFnpVeG1wTSY07PdjeFckPe/FdbSBTpy1M7G3PJ2v26rwiVjGN3Rsng+OPhE1EJGXIWndMtmC3FrqORR4HXdM=
  app: acebook-bcds
  on:
    repo: soroushh/acebook-bcds
